### ISSUE TITLE
[Help] Error when trying to build suricata 5.0.0 and dpdk 18.11.2

### ISSUE THREAD

**Issue by Onotoko** [vipinpv85/DPDK_SURICATA-4_1_1#9] opened 2020-01-15 09:23 UTC
Hello @vipinpv85,
I have tried to build suricata 5.0.0 with dpdk 18.11.2 and I got an error:

```
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:134:2: error: expected specifier-qualifier-list before ‘STAILQ_ENTRY’
  STAILQ_ENTRY(rte_mempool_objhdr) next; /**< Next in list. */
  ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:149:1: warning: data definition has no type or storage class [enabled by default]
 STAILQ_HEAD(rte_mempool_objhdr_list, rte_mempool_objhdr);
 ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:149:1: warning: type defaults to ‘int’ in declaration of ‘STAILQ_HEAD’ [enabled by default]
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:149:1: warning: parameter names (without types) in function declaration [enabled by default]
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:168:1: warning: data definition has no type or storage class [enabled by default]
 STAILQ_HEAD(rte_mempool_memhdr_list, rte_mempool_memhdr);
 ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:168:1: warning: type defaults to ‘int’ in declaration of ‘STAILQ_HEAD’ [enabled by default]
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:168:1: warning: parameter names (without types) in function declaration [enabled by default]
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:174:2: warning: ‘struct rte_mempool_memhdr’ declared inside parameter list [enabled by default]
  void *opaque);
  ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:174:2: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:183:2: error: expected specifier-qualifier-list before ‘STAILQ_ENTRY’
  STAILQ_ENTRY(rte_mempool_memhdr) next; /**< Next in list. */
  ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:250:33: error: field ‘elt_list’ has incomplete type
  struct rte_mempool_objhdr_list elt_list; /**< List of objects in pool */
                                 ^
/dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:252:33: error: field ‘mem_list’ has incomplete type
  struct rte_mempool_memhdr_list mem_list; /**< List of memory chunks */
                                 ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h: In function ‘rte_mempool_from_obj’:
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:329:12: error: ‘struct rte_mempool_objhdr’ has no member named ‘mp’
  return hdr->mp;
            ^
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h: In function ‘rte_mempool_virt2iova’:
dpdk-stable-18.11.2/x86_64-native-linuxapp-gcc/include/rte_mempool.h:1614:12: error: ‘const struct rte_mempool_objhdr’ has no member named ‘iova’

```

I tried to run your code with dpdk 18.11.2 and it had no problem. but when I change it to suricata 5.0.0 it got a problem above.

Could you give me more comment for this situation?
Thanks in advance!

**Comment by vipinpv85** [comment] 2020-01-15 09:56
I am assuming you have copied over the changes from baseline suricata 4.1.1 and tried building. Best of luck with the same.

With respect to issue you are facing, these are been discussed in couple of tickets in 3.0 and 4.1.1. it is not dpdk build issue, but more of autoconf and make ordering.

**Comment by vipinpv85** [comment] 2020-01-15 09:57
I am closing the ticket and marking it invalid as it is not representing the project.

**Closed as completed by vipinpv85** 2020-01-15 09:57 UTC
Labels: help wanted, question, wontfix

**Comment by Onotoko** [comment] 2020-01-16 02:08
Thank you @vipinpv85 ,
Let me check again makefile, configure ... once again

**Comment by mjasojedov** [comment] 2020-03-12 17:03
@Onotoko Hi, have you found the solution for your issue? I am facing the same one.

**Comment by vipinpv85** [comment] 2020-03-12 22:54
@Onotoko and @mjasojedov the issue that you are facing is because of ordering in include files. The solution is to include dpdk.ueaders first.

**Comment by vipinpv85** [comment] 2020-07-05 06:32
@Onotoko  and @mjasojedov  there are no updates from your, happy to say the issue is found and fixed in the current repository. Happy hunting
